module.exports = {
    plugins: ['import'],
    rules: {
        'import/default': 2,
        'import/export': 2,
        'import/extensions': 2,
        'import/imports-first': 2,
        'import/named': 2,
        'import/namespace': 2,
        'import/newline-after-import': 2,
        'import/no-amd': 2,
        'import/no-commonjs': 0,
        'import/no-deprecated': 2,
        'import/no-duplicates': 2,
        'import/no-extraneous-dependencies': 2,
        'import/no-mutable-exports': 2,
        'import/no-named-as-default': 2,
        'import/no-named-as-default-member': 2,
        'import/no-namespace': 0,
        'import/no-nodejs-modules': 0,
        'import/no-unresolved': [2, {commonjs: true, amd: true}],
        'import/order': 2,
        'import/prefer-default-export': 0,
    },
    settings: {
        'import/ignore': ['node_modules', '.(jpe?g|gif|json|scss|png|svg)'],
        'import/resolver': 'webpack',
    },
};
