module.exports = {
    "rules": {
        "array-bracket-spacing": 2,
        "block-spacing": 2,
        "brace-style": 2,
        "camelcase": [2, {
            "properties": "never"
        }],
        "comma-spacing": 2,
        "comma-style": 2,
        "computed-property-spacing": 2,
        "consistent-this": 2,
        "eol-last": 2,
        "func-names": 2,
        "func-style": 0,
        "id-length": [2, {
            "exceptions": ["_", "a", "b"]
        }],
        "id-match": 2,
        "indent": [2, 4, {
            "SwitchCase": 1,
        }],
        "jsx-quotes": 2,
        "key-spacing": [0, {
            "align": "value",
            "beforeColon": false,
            "afterColon": true
        }],
        "lines-around-comment": 2,
        "linebreak-style": 2,
        "max-nested-callbacks": 2,
        "new-cap": 2,
        "new-parens": 2,
        "newline-after-var": 0,
        "no-array-constructor": 2,
        "no-continue": 2,
        "no-inline-comments": 2,
        "no-lonely-if": 2,
        "no-mixed-spaces-and-tabs": 2,
        "no-multiple-empty-lines": 2,
        "no-nested-ternary": 2,
        "no-negated-condition": 2,
        "no-new-object": 2,
        "no-restricted-syntax": 2,
        "no-spaced-func": 2,
        "no-ternary": 0,
        "no-trailing-spaces": 2,
        "no-underscore-dangle": 2,
        "no-unneeded-ternary": 2,
        "object-curly-spacing": 2,
        "one-var": 0,
        "operator-assignment": 2,
        "operator-linebreak": 2,
        "padded-blocks": [2, "never"],
        "quote-props": [2, "consistent-as-needed"],
        "quotes": [2, "single"],
        "require-jsdoc": 1,
        "semi-spacing": 2,
        "semi": 2,
        "sort-vars": 2,
        "space-after-keywords": 2,
        "space-before-keywords": 2,
        "space-before-blocks": 2,
        "space-before-function-paren": [2, {
            "anonymous": "always",
            "named": "never"
        }],
        "space-in-parens": 2,
        "space-infix-ops": 2,
        "space-return-throw-case": 2,
        "space-unary-ops": 2,
        "spaced-comment": 0,
        "wrap-regex": 2,
    },
};