module.exports = {
    rules: {
        // 'array-bracket-spacing': 2,
        // 'babel/new-cap': [2, { capIsNew: false }],
        // 'babel/object-curly-spacing': [2, 'never'],
        // 'block-spacing': 2,
        // 'brace-style': 2,
        // camelcase: [2, { properties: 'never' }],
        // 'comma-dangle': [2, 'always-multiline'],
        // 'comma-spacing': 2,
        // 'comma-style': 2,
        // 'computed-property-spacing': 2,
        // 'consistent-this': 2,
        // 'eol-last': 2,
        // 'func-call-spacing': 2,
        // 'func-names': 2,
        // 'nonblock-statement-body-position': 2,
        // 'func-style': 0,
        // 'id-blacklist': 2,
        // 'id-length': 0,
        // 'id-match': 2,
        // indent: [2, 4, { SwitchCase: 1 }],
        // 'jsx-quotes': 2,
        // 'key-spacing': 2,
        // 'keyword-spacing': 2,
        // 'line-comment-position': 2,
        // 'linebreak-style': 2,
        // 'lines-around-comment': 2,
        // 'lines-around-directive': 2,
        // 'max-depth': 2,
        // 'max-len': 0,
        // 'max-lines': 0,
        // 'max-nested-callbacks': 2,
        // 'max-params': 0,
        // 'max-statements': 0,
        // 'max-statements-per-line': 2,
        // 'multiline-ternary': 0,
        // 'new-parens': 2,
        // 'newline-after-var': 0,
        // 'newline-before-return': 2,
        // 'newline-per-chained-call': 0,
        // 'no-array-constructor': 2,
        // 'no-bitwise': 2,
        // 'no-continue': 2,
        // 'no-inline-comments': 2,
        // 'no-lonely-if': 2,
        // 'no-mixed-operators': 2,
        // 'no-mixed-spaces-and-tabs': 2,
        // 'no-multi-assign': 0,
        // 'no-multiple-empty-lines': 2,
        // 'no-negated-condition': 2,
        // 'no-nested-ternary': 2,
        // 'no-new-object': 2,
        // 'no-plusplus': 0,
        // 'no-restricted-syntax': 2,
        // 'no-tabs': 2,
        // 'no-ternary': 0,
        // 'no-trailing-spaces': 2,
        // 'no-underscore-dangle': [
        //     2,
        //     { allow: ['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'] },
        // ],
        // 'no-unneeded-ternary': 2,
        // 'no-whitespace-before-property': 2,
        // 'object-curly-newline': 0,
        // 'object-property-newline': 0,
        // 'one-var': 0,
        // 'one-var-declaration-per-line': 2,
        // 'operator-assignment': 2,
        // 'operator-linebreak': 2,
        // 'padded-blocks': [2, 'never'],
        'quote-props': [2, 'consistent-as-needed'],
        "quotes": [1, 'single'],
        // 'require-jsdoc': 0,
        // semi: 2,
        // 'semi-spacing': 2,
        // 'sort-keys': 0,
        // 'sort-vars': 2,
        // 'space-before-blocks': 2,
        // 'space-before-function-paren': [
        //     2,
        //     { anonymous: 'always', named: 'never' },
        // ],
        // 'space-in-parens': 2,
        // 'space-infix-ops': 2,
        // 'space-unary-ops': 2,
        // 'spaced-comment': 0,
        // 'template-tag-spacing': 2,
        // 'unicode-bom': 2,
        // 'wrap-regex': 2,
    },
};
